/**
 * ᴍᴀɴɪ 𝗠𝗗 ☘ - Combined Server Entry Point
 * WhatsApp Bot + Express Web Server + Socket.IO + Keep-Alive Monitor
 * 
 * v3.0.10: Simplified - pairing code auto-generated by bot, web UI just reads it
 * - No runtime pairing logic in server.js
 * - Bot auto-generates pairing code on startup (when not registered)
 * - Web UI polls /api/pairing-code for the pre-generated code
 * - /api/pair just clears session and triggers a restart for fresh pairing
 */

const express = require('express');
const http = require('http');
const path = require('path');
const os = require('os');
const fs = require('fs');

// ============================================
// 1. CREATE EXPRESS SERVER
// ============================================
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'web')));

// Health check endpoint
app.get('/api/health', (req, res) => {
  const uptime = process.uptime();
  const memUsage = process.memoryUsage();
  const totalMem = os.totalmem();
  const freeMem = os.freemem();
  const usedMem = totalMem - freeMem;
  
  res.json({
    status: global.waSocket && global.waSocket.user ? 'online' : 'offline',
    bot: 'ᴍᴀɴɪ 𝗠𝗗 ☘',
    uptime: uptime,
    memory: (memUsage.rss / 1024 / 1024).toFixed(2) + ' MB',
    memoryUsagePercent: ((usedMem / totalMem) * 100).toFixed(2),
    cpuUsage: (os.loadavg()[0] * 100 / os.cpus().length).toFixed(2),
    totalUsers: totalUsers,
    activeSockets: activeSockets,
    botConnected: !!(global.waSocket && global.waSocket.user),
    timestamp: new Date().toISOString()
  });
});

// Ping endpoint for uptime monitors
app.get('/ping', (req, res) => {
  res.send('Bot is alive! ✅');
});

// Pair device page redirect
app.get('/pair-device', (req, res) => {
  res.redirect('/');
});

// ============================================
// PAIRING CODE REST API
// ============================================

// Get current pairing code (web UI polls this every 3 seconds)
app.get('/api/pairing-code', (req, res) => {
  try {
    const bot = require('./index');
    const data = bot.readPairingCode();
    if (data) {
      res.json({ code: data.code, number: data.number, timestamp: data.timestamp });
    } else {
      res.json({ code: null, status: 'waiting', message: 'Waiting for pairing code...' });
    }
  } catch (e) {
    res.json({ code: null, error: e.message });
  }
});

// Request fresh pairing code (clears session and triggers restart)
app.post('/api/pair', async (req, res) => {
  const { number } = req.body;
  const cleanNumber = (number || '').replace(/[^0-9]/g, '');
  
  if (!cleanNumber || cleanNumber.length < 10) {
    return res.status(400).json({ error: 'Invalid number. Enter phone with country code.' });
  }

  console.log(`📱 [API] Fresh pairing requested for: ${cleanNumber}`);

  // Save the number so the bot can use it on restart
  try {
    const phoneFile = path.join(__dirname, 'pairing-phone.txt');
    fs.writeFileSync(phoneFile, cleanNumber);
  } catch (e) {
    console.error('Could not save phone number:', e.message);
  }

  // Clear existing pairing code
  try {
    const bot = require('./index');
    bot.clearPairingCode();
  } catch (e) {}

  // Clear session files
  try {
    const sessionDir = path.join(__dirname, 'session');
    if (fs.existsSync(sessionDir)) {
      fs.rmSync(sessionDir, { recursive: true, force: true });
      fs.mkdirSync(sessionDir, { recursive: true });
    }
  } catch (e) {}

  // Respond immediately
  res.json({ 
    status: 'restarting', 
    message: 'Session cleared. Bot is restarting with fresh pairing mode...',
    pairingNumber: cleanNumber
  });

  // Restart the bot process (Render will auto-restart)
  setTimeout(() => {
    console.log('🔄 [API] Restarting bot for fresh pairing...');
    process.exit(0);
  }, 2000);
});

// ============================================
// 2. START HTTP SERVER FIRST
// ============================================
const server = http.createServer(app);

// ============================================
// 3. SOCKET.IO SETUP
// ============================================
const { Server: SocketServer } = require('socket.io');
const io = new SocketServer(server, {
  cors: {
    origin: '*',
    methods: ['GET', 'POST']
  }
});

// Expose io instance globally so index.js can broadcast pairing codes
global.ioInstance = io;

let users = new Map();
let totalUsers = 0;
let activeSockets = 0;

io.on('connection', (socket) => {
  activeSockets++;
  console.log(`🔌 [SOCKET] New connection: ${socket.id} | Active: ${activeSockets}`);

  socket.on('set-user', (userId) => {
    users.set(userId, socket.id);
    totalUsers++;
    console.log(`👤 [SOCKET] User registered: ${userId}`);
  });

  socket.on('disconnect', () => {
    activeSockets--;
    console.log(`🔌 [SOCKET] Disconnected: ${socket.id} | Active: ${activeSockets}`);
  });
});

// Broadcast stats every 5 seconds
setInterval(() => {
  io.emit('stats', {
    activeSockets: activeSockets,
    totalUsers: totalUsers,
    botConnected: !!(global.waSocket && global.waSocket.user)
  });
}, 5000);

// ============================================
// Deploy webhook endpoint
// ============================================
app.get('/deploy', async (req, res) => {
  const token = req.query.key;
  const expectedToken = 'svdYViZ5-dk';
  
  if (token !== expectedToken) {
    return res.status(403).json({ error: 'Invalid deploy token' });
  }
  
  console.log('🚀 [DEPLOY] Deploy webhook triggered!');
  res.json({ status: 'deploy-triggered', message: 'Bot is redeploying...' });
  
  setTimeout(() => {
    console.log('🔄 [DEPLOY] Restarting bot...');
    process.exit(0);
  }, 2000);
});

// ============================================
// 4. START LISTENING
// ============================================
server.listen(PORT, '0.0.0.0', () => {
  console.log(`\n🌐 [WEB SERVER] Running on port ${PORT}`);
  console.log(`🌐 [WEB SERVER] Pair Device: http://localhost:${PORT}/`);
  console.log(`🌐 [WEB SERVER] Health: http://localhost:${PORT}/api/health`);
  console.log(`🌐 [WEB SERVER] Pairing API: http://localhost:${PORT}/api/pairing-code\n`);
});

// ============================================
// 5. KEEP-ALIVE / UPTIME MONITOR
// ============================================
console.log('🔥 [KEEP-ALIVE] Starting uptime monitor...');

const EXTERNAL_URL = process.env.RENDER_EXTERNAL_URL || process.env.APP_URL;

if (EXTERNAL_URL) {
  console.log(`🚀 [KEEP-ALIVE] Self-pinging enabled for: ${EXTERNAL_URL}`);
  setInterval(() => {
    const pingUrl = EXTERNAL_URL.endsWith('/') ? `${EXTERNAL_URL}ping` : `${EXTERNAL_URL}/ping`;
    http.get(pingUrl, (res) => {
      console.log(`📡 [KEEP-ALIVE] Self-ping sent to ${pingUrl} | Status: ${res.statusCode}`);
    }).on('error', (err) => {
      console.error(`❌ [KEEP-ALIVE] Self-ping failed: ${err.message}`);
    });
  }, 2 * 60 * 1000);
} else {
  console.log('⚠️ [KEEP-ALIVE] RENDER_EXTERNAL_URL not set. Bot might sleep on Render free tier.');
}

// Log heartbeat every 2 minutes
setInterval(() => {
  const uptime = process.uptime();
  const days = Math.floor(uptime / 86400);
  const hours = Math.floor((uptime % 86400) / 3600);
  const minutes = Math.floor((uptime % 3600) / 60);
  const memMB = (process.memoryUsage().rss / 1024 / 1024).toFixed(2);
  console.log(`\n🔥 [KEEP-ALIVE] Bot is alive! Uptime: ${days}d ${hours}h ${minutes}m | Memory: ${memMB} MB | Sockets: ${activeSockets}`);
}, 120000);

// Auto-restart if memory too high
setInterval(() => {
  const used = process.memoryUsage().rss / 1024 / 1024;
  if (used > 900) {
    console.log(`⚠️ [KEEP-ALIVE] RAM too high (${used.toFixed(0)}MB), restarting...`);
    process.exit(1);
  }
}, 30000);

// ============================================
// 6. START WHATSAPP BOT
// ============================================
console.log('🤖 [BOT] Starting WhatsApp Bot...\n');

process.env.PORT = PORT;

const bot = require('./index');
console.log('🤖 [BOT] WhatsApp Bot module loaded');

// Automatically start the bot on server boot
bot.startXeonBotInc().then(() => {
  console.log('🤖 [BOT] WhatsApp Bot started successfully');
}).catch(err => {
  console.error('❌ [BOT] Failed to start WhatsApp Bot:', err);
});
